#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../../../../../vite@5.4.4_@types+node@22.5.4_lightningcss@1.27.0_terser@5.32.0/node_modules/vite/bin/vite.js" "$@"
else
  exec node  "$basedir/../../../../../../vite@5.4.4_@types+node@22.5.4_lightningcss@1.27.0_terser@5.32.0/node_modules/vite/bin/vite.js" "$@"
fi
